server:
  # 启用 gzip 压缩
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
  error:
    includeException: true
    includeStacktrace: ALWAYS
    includeMessage: ALWAYS
  servlet:
    context-path: /geex-guts-camunda
  port: 8081

spring:
  application:
    name: geex-guts-camunda
  datasource:
    #mysql
    url: jdbc:mysql://localhost:3306/camunda_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


app:
  id: geex-guts-camunda
apollo:
  bootstrap:
    enabled: true



#actuator
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
      base-path: /metrics
  endpoint:
    health:
      show-details: always
