server:
  # 启用 gzip 压缩
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
  error:
    includeException: true
    includeStacktrace: ALWAYS
    includeMessage: ALWAYS
  servlet:
    context-path: /yucong

#actuator
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
      base-path: /metrics
  endpoint:
    health:
      show-details: always

spring:
  profiles:
    active: apollo