api2d:
  api:
    base: https://openai.api2d.net/
    key: fk206636-nQpZFfhl65GplHaVtyKfZ0zeePcLZAeV

bce:
  client:
    id: xxx
    secret: xxx

yucong:
  action:
    rest:
      url: http://192.168.8.12:8180/yc-action-server
  conversation:
    expire: 300

milvus:
  host: 127.0.0.1
  port: 19530

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yucong_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123