server:
  # 启用 gzip 压缩
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
  error:
    includeException: true
    includeStacktrace: ALWAYS
    includeMessage: ALWAYS
  servlet:
    context-path: /geex-guts-camunda
  port: 8081

spring:
  application:
    name: geex-guts-camunda
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/camunda_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

#  camunda配置
camunda:
  bpm:
  # 配置账户密码来访问Camunda自带的管理界面
    admin-user:
      id: admin
      password: admin
      first-name: admin
    filter:
      create: All tasks
#actuator
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
      base-path: /metrics
  endpoint:
    health:
      show-details: always
